### ISSUE TITLE
generate .github/workflows/pygbag.yml

### ISSUE THREAD

**Issue by pmp-p** [pygame-web/pygbag#52]
automatically, with maybe `--gh` and add "/build/web" and "/build/web-cache" to .gitignore

```
name: pygbag_build
on: [workflow_dispatch]

jobs:  
  build-pygbag:
    name: Build for Emscripten pygbag runtime
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
            python3 -m pip install pygbag
            python3 -m pygbag --build $GITHUB_WORKSPACE/main.py
    - name : "Upload to GitHub pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: build/web

```
